apiVersion: app/v1
kind: Deployment
metadata:
  name: api-counting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-counting
  template:
    metadata:
      labels:
        app: api-counting
    spec:
      containers:
        - name: api-counting
          image: geeksky/api-counting:latest
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-password
      volumes:
        - name: caching
          emptyDir: {}