apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  type: ClusterIP
  ports:
    - port: 3033
      targetPort: 3033
    - port: 4040
      targetPort: 4040
  selector:
    app: spark-master