apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark
          env:
            - name: SPARK_MASTER_URL
              value: "spark://spark-master-service:7077"
          ports:
            - containerPort: 4044