apiVersion: app/v1
kind: Deployment
metadata:
  name: api-rust-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-rust-server
  template:
    metadata:
      labels:
        app: api-rust-server
    spec:
      containers:
        - name: api-rust-server
          image: geeksky/api-rust:latest
          ports:
            - containerPort: 8085
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-password
      volumes:
        - name: caching
          emptyDir: {}